# Site settings
name: 观星客
location: 扬州
school: 扬州大学
github: https://github.com/
facebook: https://www.facebook.com/
phone: XXXXXXXXXXX
email: szzsf1999@163.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

